/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Base schema for addressable entities
 *
 * @param href Hyperlink reference
 * @param id unique identifier
 */


interface Addressable {

    /* Hyperlink reference */
    @get:JsonProperty("href")
    val href: kotlin.String?
    /* unique identifier */
    @get:JsonProperty("id")
    val id: kotlin.String?
}

