/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Entity
import org.openapitools.client.models.FooRefOrValue

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param atType When sub-classing, this defines the sub-class Extensible name
 * @param barPropA 
 * @param fooPropB 
 * @param foo 
 * @param href Hyperlink reference
 * @param atSchemaLocation A URI to a JSON-Schema file that defines additional attributes and relationships
 * @param atBaseType When sub-classing, this defines the super-class
 */


data class Bar (

    @field:JsonProperty("id")
    override val id: kotlin.String,

    /* When sub-classing, this defines the sub-class Extensible name */
    @field:JsonProperty("@type")
    override val atType: kotlin.String,

    @field:JsonProperty("barPropA")
    val barPropA: kotlin.String? = null,

    @field:JsonProperty("fooPropB")
    val fooPropB: kotlin.String? = null,

    @field:JsonProperty("foo")
    val foo: FooRefOrValue? = null,

    /* Hyperlink reference */
    @field:JsonProperty("href")
    override val href: kotlin.String? = null,

    /* A URI to a JSON-Schema file that defines additional attributes and relationships */
    @field:JsonProperty("@schemaLocation")
    override val atSchemaLocation: kotlin.String? = null,

    /* When sub-classing, this defines the super-class */
    @field:JsonProperty("@baseType")
    override val atBaseType: kotlin.String? = null

) : Entity,BarRefOrValue

