/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * Entity reference schema to be use for all entityRef class.
 *
 * @param atType When sub-classing, this defines the sub-class Extensible name
 * @param name Name of the related entity.
 * @param atReferredType The actual type of the target instance when needed for disambiguation.
 * @param href Hyperlink reference
 * @param id unique identifier
 * @param atSchemaLocation A URI to a JSON-Schema file that defines additional attributes and relationships
 * @param atBaseType When sub-classing, this defines the super-class
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = BarRef::class, name = "BarRef"),
    JsonSubTypes.Type(value = FooRef::class, name = "FooRef")
)

interface EntityRef : Addressable, Extensible {

    /* When sub-classing, this defines the sub-class Extensible name */
    @get:JsonProperty("@type")
    override val atType: kotlin.String
    /* Name of the related entity. */
    @get:JsonProperty("name")
    val name: kotlin.String?
    /* The actual type of the target instance when needed for disambiguation. */
    @get:JsonProperty("@referredType")
    val atReferredType: kotlin.String?
    /* Hyperlink reference */
    @get:JsonProperty("href")
    override val href: kotlin.String?
    /* unique identifier */
    @get:JsonProperty("id")
    override val id: kotlin.String?
    /* A URI to a JSON-Schema file that defines additional attributes and relationships */
    @get:JsonProperty("@schemaLocation")
    override val atSchemaLocation: kotlin.String?
    /* When sub-classing, this defines the super-class */
    @get:JsonProperty("@baseType")
    override val atBaseType: kotlin.String?
}

