/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * 
 *
 * @param atType When sub-classing, this defines the sub-class Extensible name
 * @param href Hyperlink reference
 * @param id unique identifier
 * @param atSchemaLocation A URI to a JSON-Schema file that defines additional attributes and relationships
 * @param atBaseType When sub-classing, this defines the super-class
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = Bar::class, name = "Bar"),
    JsonSubTypes.Type(value = BarCreate::class, name = "Bar_Create"),
    JsonSubTypes.Type(value = Foo::class, name = "Foo"),
    JsonSubTypes.Type(value = Pasta::class, name = "Pasta"),
    JsonSubTypes.Type(value = Pizza::class, name = "Pizza"),
    JsonSubTypes.Type(value = PizzaSpeziale::class, name = "PizzaSpeziale")
)

interface Entity : Addressable, Extensible {

    /* When sub-classing, this defines the sub-class Extensible name */
    @get:JsonProperty("@type")
    override val atType: kotlin.String
    /* Hyperlink reference */
    @get:JsonProperty("href")
    override val href: kotlin.String?
    /* unique identifier */
    @get:JsonProperty("id")
    override val id: kotlin.String?
    /* A URI to a JSON-Schema file that defines additional attributes and relationships */
    @get:JsonProperty("@schemaLocation")
    override val atSchemaLocation: kotlin.String?
    /* When sub-classing, this defines the super-class */
    @get:JsonProperty("@baseType")
    override val atBaseType: kotlin.String?
}

