/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param atType When sub-classing, this defines the sub-class Extensible name
 * @param atSchemaLocation A URI to a JSON-Schema file that defines additional attributes and relationships
 * @param atBaseType When sub-classing, this defines the super-class
 */


interface Extensible {

    /* When sub-classing, this defines the sub-class Extensible name */
    @get:JsonProperty("@type")
    val atType: kotlin.String
    /* A URI to a JSON-Schema file that defines additional attributes and relationships */
    @get:JsonProperty("@schemaLocation")
    val atSchemaLocation: kotlin.String?
    /* When sub-classing, this defines the super-class */
    @get:JsonProperty("@baseType")
    val atBaseType: kotlin.String?
}

