/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Entity

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param atType When sub-classing, this defines the sub-class Extensible name
 * @param pizzaSize 
 * @param href Hyperlink reference
 * @param id unique identifier
 * @param atSchemaLocation A URI to a JSON-Schema file that defines additional attributes and relationships
 * @param atBaseType When sub-classing, this defines the super-class
 */


open class Pizza (

    /* When sub-classing, this defines the sub-class Extensible name */
    @field:JsonProperty("@type")
    override open val atType: kotlin.String,

    @field:JsonProperty("pizzaSize")
    open val pizzaSize: java.math.BigDecimal? = null,

    /* Hyperlink reference */
    @field:JsonProperty("href")
    override open val href: kotlin.String? = null,

    /* unique identifier */
    @field:JsonProperty("id")
    override open val id: kotlin.String? = null,

    /* A URI to a JSON-Schema file that defines additional attributes and relationships */
    @field:JsonProperty("@schemaLocation")
    override open val atSchemaLocation: kotlin.String? = null,

    /* When sub-classing, this defines the super-class */
    @field:JsonProperty("@baseType")
    override open val atBaseType: kotlin.String? = null

) : Entity {

}

