/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Pizza

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param atType When sub-classing, this defines the sub-class Extensible name
 * @param toppings 
 * @param href Hyperlink reference
 * @param id unique identifier
 * @param atSchemaLocation A URI to a JSON-Schema file that defines additional attributes and relationships
 * @param atBaseType When sub-classing, this defines the super-class
 * @param pizzaSize 
 */


data class PizzaSpeziale (

    /* When sub-classing, this defines the sub-class Extensible name */
    @field:JsonProperty("@type")
    override val atType: kotlin.String,

    @field:JsonProperty("toppings")
    val toppings: kotlin.String? = null,

    /* Hyperlink reference */
    @field:JsonProperty("href")
    override val href: kotlin.String? = null,

    /* unique identifier */
    @field:JsonProperty("id")
    override val id: kotlin.String? = null,

    /* A URI to a JSON-Schema file that defines additional attributes and relationships */
    @field:JsonProperty("@schemaLocation")
    override val atSchemaLocation: kotlin.String? = null,

    /* When sub-classing, this defines the super-class */
    @field:JsonProperty("@baseType")
    override val atBaseType: kotlin.String? = null,

    @field:JsonProperty("pizzaSize")
    override val pizzaSize: java.math.BigDecimal? = null

) : Pizza(
    atType = atType,
    pizzaSize = pizzaSize,
    href = href,
    id = id,
    atSchemaLocation = atSchemaLocation,
    atBaseType = atBaseType)

